apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "cosmo-traefik.labels" . | nindent 4 }}
  name: cosmo-auth-server
rules:
  - apiGroups:
      - cosmo-workspace.github.io
    resources:
      - users
    verbs:
      - get
      - list
  - apiGroups:
      - cosmo-workspace.github.io
    resources:
      - users/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: 
    {{- include "cosmo-traefik.labels" . | nindent 4 }}
  name: cosmo-auth-server-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cosmo-dashboard
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: {{ .Release.Namespace }}
